CREATE TABLE TB_USUARIO (
    ID_USUARIO   NUMBER(19)        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NM_USUARIO   VARCHAR2(120)     NOT NULL,
    DS_EMAIL     VARCHAR2(150)     NOT NULL,
    DS_SENHA     VARCHAR2(255)     NOT NULL,
    DS_ROLE      VARCHAR2(20)      DEFAULT 'USER' NOT NULL,
    DT_CRIACAO   TIMESTAMP         DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_USUARIO_EMAIL UNIQUE (DS_EMAIL),
    CONSTRAINT CK_USUARIO_ROLE CHECK (DS_ROLE IN ('USER','ADMIN'))
);

CREATE INDEX IX_USUARIO_EMAIL ON TB_USUARIO (DS_EMAIL);
