CREATE TABLE denuncias (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(150) NOT NULL,
    descricao VARCHAR2(2000) NOT NULL,
    endereco VARCHAR2(255) NOT NULL,
    bairro VARCHAR2(120) NOT NULL,
    cidade VARCHAR2(120) NOT NULL,
    estado VARCHAR2(2) NOT NULL,
    latitude NUMBER(10, 7) NOT NULL,
    longitude NUMBER(10, 7) NOT NULL,
    categoria VARCHAR2(40) NOT NULL,
    status VARCHAR2(30) NOT NULL,
    usuario_id NUMBER(19) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP,
    CONSTRAINT fk_denuncias_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_denuncias_categoria CHECK (categoria IN (
        'ENTULHO', 'CONCRETO', 'MADEIRA', 'GESSO', 'METAL', 'PLASTICO', 'VIDRO', 'MISTO', 'OUTROS'
    )),
    CONSTRAINT ck_denuncias_status CHECK (status IN (
        'ABERTA', 'EM_ANALISE', 'EM_ANDAMENTO', 'RESOLVIDA', 'ARQUIVADA'
    ))
);

CREATE INDEX idx_denuncias_usuario ON denuncias (usuario_id);
CREATE INDEX idx_denuncias_cidade ON denuncias (cidade, estado);
