CREATE TABLE TB_DENUNCIA (
    ID_DENUNCIA       NUMBER(19)        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NM_TITULO         VARCHAR2(150)     NOT NULL,
    DS_DESCRICAO      VARCHAR2(2000)    NOT NULL,
    DS_ENDERECO       VARCHAR2(200)     NOT NULL,
    NM_BAIRRO         VARCHAR2(100)     NOT NULL,
    NM_CIDADE         VARCHAR2(100)     NOT NULL,
    SG_ESTADO         VARCHAR2(2)       NOT NULL,
    VL_LATITUDE       NUMBER(10,7)      NOT NULL,
    VL_LONGITUDE      NUMBER(10,7)      NOT NULL,
    DS_CATEGORIA      VARCHAR2(30)      NOT NULL,
    DS_STATUS         VARCHAR2(20)      DEFAULT 'PENDENTE' NOT NULL,
    ID_USUARIO        NUMBER(19)        NOT NULL,
    DT_CRIACAO        TIMESTAMP         DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO    TIMESTAMP,
    CONSTRAINT FK_DENUNCIA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO),
    CONSTRAINT CK_DENUNCIA_CATEGORIA CHECK (DS_CATEGORIA IN (
        'CONCRETO','MADEIRA','METAL','GESSO','CERAMICA','PLASTICO','TINTAS_E_SOLVENTES','MISTO','OUTROS'
    )),
    CONSTRAINT CK_DENUNCIA_STATUS CHECK (DS_STATUS IN (
        'PENDENTE','EM_ANALISE','EM_ATENDIMENTO','RESOLVIDA','CANCELADA'
    ))
);

CREATE INDEX IX_DENUNCIA_USUARIO ON TB_DENUNCIA (ID_USUARIO);
CREATE INDEX IX_DENUNCIA_STATUS  ON TB_DENUNCIA (DS_STATUS);
CREATE INDEX IX_DENUNCIA_CIDADE  ON TB_DENUNCIA (NM_CIDADE);
